name: ovbot

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Build
        run: |
          sudo apt-get -q update
          sudo apt-get install automake
          sudo apt-get install git
          sudo apt-get install build-essential
          sudo apt-get install gettext
          sudo apt-get install python2-dev
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8 future
          pip3 install Pillow
          ./CI/build.sh
